version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          name: Restore `package.json` cache
          keys:
            - v3-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-deps-{{ .Branch }}
            - v3-deps
      - run:
          name: Install Node Modules using 'npm install'
          command: npm install
      - save_cache:
          name: Save cache both node moduls and Cypress!
          key: v3-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both node modules and Cypress!
      - run:
          name: Run Cypress Tests Suite
          command: npm test
      
      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: reports/videos
      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: reports/screenshots
      - store_artifacts:
          name: Uploading allure-report artifacts
          path: reports
      